#!/bin/bash

export CARGO_HOME=".idea/.cargo" \
&& export RUSTUP_HOME=".idea/.rustup" \
&& source "$CARGO_HOME/env" \
&& rustup default nightly \
&& cargo clean \
&& cargo build --target wasm32-unknown-unknown \
&& cp target/wasm32-unknown-unknown/debug/enscry.wasm src/.wasm \
&& cargo clean \

